lilac_website/home/urls.py
# coding: utf-8
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
app_name = 'home'

urlpatterns = [
    #显示主页
    path('', views.show_home, name = 'homepage')
]

lilac_website/lilac_website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('project/', include('project.urls', namespace='project')),
    path('user/', include('user.urls', namespace='user')),
    path('comment/', include('comment.urls', namespace='comment')),
    path('', include('home.urls', namespace='home')),
]

# 增加媒体文件文件的路径
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lilac_website/project/urls.py
# coding: utf-8
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
app_name = 'project'

urlpatterns = [
    # 项目列表
    path('list/', views.project_view().show_list, name = 'project_list'),
    # 项目详情
    path('detail/<int:id>/', views.project_view().show_detail, name = 'project_detail'),
    # 发布新项目
    path('create/', views.project_view().project_create, name = 'project_create'),
    # 更新项目
    path('update/<int:id>/', views.project_view().project_update, name = 'project_update'),
    # （安全）删除项目
    path('safe_delete/<int:id>/', views.project_view().project_delete, name = 'project_safe_delete'),
    # 添加申请者
    path('apply/<int:id>/', views.project_view().project_apply, name = 'project_apply')
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lilac_website/user/urls.py
# coding: utf-8
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    # 用户登录
    path('login/', views.user_login, name='login'),
    # 用户退出
    path('logout/', views.user_logout, name='logout'),
    # 用户注册
    path('register/', views.UserRegisterView.as_view(), name='register'),
    # 用户编辑个人信息
    path('edituserinfo/<int:id>/', views.UserInfoChangeView.as_view(), name='edituserinfo'),
    # 查看用户信息
    path('userinfo/<int:id>/', views.user_info, name='userinfo'),
    # 用户信息验证
    path('user-signinup-validate', views.user_signup_in_validate, name='user_signinup_validate'),
]

lilac_website/templates/base.html
<!-- 载入静态文件 -->
{% load staticfiles %}

<!DOCTYPE html>
<!-- 网站主语言 -->
<html lang="zh-cn">

<head>
    <!-- 网站采用的字符编码 -->
    <meta charset="utf-8">
    <!-- 预留网站标题的位置 -->
    <title>{% block title %}{% endblock %}</title>
    <!-- 引入bootstrap的css文件 -->
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
</head>

<body>
    <!-- 引入导航栏 -->
    {% include 'header.html' %}
    <!-- 预留具体页面的位置 -->
    {% block content %}{% endblock content %}
    <!-- 引入注脚 -->
    {% include 'footer.html' %}
    <!-- bootstrap.js 依赖 jquery.js 和popper.js，因此在这里引入 -->
    <script src="{% static 'jquery/jquery-3.4.1.min.js' %}"></script>
    <script src="{% static 'popper/popper.js' %}"></script>    
    <script src="{% static 'layer/layer.js' %}"></script>
    <!-- 引入bootstrap的js文件 -->
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <!-- 引入JS -->
    {% block script %}{% endblock %}
</body>

</html>

lilac_website/templates/footer.html
{% load staticfiles %}
<!-- Footer -->
<div>
    <br><br><br>
</div>
<footer class="py-3 bg-dark fixed-bottom">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; lilac.hit.edu.cn 2018</p>
    </div>
</footer>

lilac_website/templates/header.html
<!-- 定义导航栏 -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">

    <!-- 导航栏商标 -->
    <a class="navbar-brand" href="">紫丁香微纳卫星创新工场</a>

    <!-- 导航入口 -->
    <div>
      <ul class="navbar-nav">
        <!-- -----------------------请*主页*相关的链接写在下方------------------------ -->
        <li class="nav-item">
          <a class="nav-link" href="{% url 'home:homepage' %}">主页</a>
        </li>
        <!-- -----------------------请*工程*相关的链接写在下方------------------------ -->
        <li class="nav-item">
          <a class="nav-link" href="{% url 'project:project_list' %}">项目列表</a>
        </li>
        <!-- -----------------------请*用户*相关的链接写在下方------------------------ -->
        {% if user.is_authenticated %}
        <!-- 如果用户已经登录，则显示用户名下拉框 -->
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false">
            {{ user.username }}
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{% url 'user:logout' %}">退出登录</a>
          </div>
        </li>
        <!-- 如果用户未登录，则显示 “登录” -->
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'user:login' %}">登录</a>
        </li>
        {% endif %}
      </ul>
    </div>

  </div>
</nav>