lilac_website/home/urls.py
# coding: utf-8
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
app_name = 'home'

urlpatterns = [
    #显示主页
    path('', views.show_home, name = 'homepage')
]

lilac_website/lilac_website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('project/', include('project.urls', namespace='project')),
    path('user/', include('user.urls', namespace='user')),
    path('comment/', include('comment.urls', namespace='comment')),
    path('', include('home.urls', namespace='home')),
]

# 增加媒体文件文件的路径
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lilac_website/user/urls.py
# coding: utf-8
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    # 用户登录
    path('login/', views.user_login, name='login'),
    # 用户退出
    path('logout/', views.user_logout, name='logout'),
    # 用户注册
    path('register/', views.UserRegisterView.as_view(), name='register'),
    # 用户编辑个人信息
    path('edituserinfo/<int:id>/', views.UserInfoChangeView.as_view(), name='edituserinfo'),
    # 查看用户信息
    path('userinfo/<int:id>/', views.user_info, name='userinfo'),
    # 用户信息验证
    path('user-signinup-validate', views.user_signup_in_validate, name='user_signinup_validate'),
]

lilac_website/user/models.py
# coding: utf-8

from django.db import models
# 引入django原生user类
from django.contrib.auth.models import User
# 引入django-ckeditor 实现富文本编辑器的功能
from ckeditor.fields import RichTextField


# Create your models here.
class School(models.Model):
    '''
    学校类， 这里用于创建可选学校
    '''
    # 学校名称
    school_name = models.CharField(max_length=50)
    # 学校域名列表, 采用JSON格式存储
    school_emails = models.CharField(max_length=500)

    class Meta:
        '''
        该类用于存储模型的别名等项目
        '''
        verbose_name = '参与学校'
        verbose_name_plural = '参与学校'

    def __str__(self):
        """
        返回模型的校名字段， 用于优化在admin页面的显示

        Args:
            None

        Returns:
            str: 返回模型的校名字段

        """
        return self.school_name


class Profile(models.Model):
    '''
    采用扩展django原生User类， 这样原生的User类用于处理登录等功能， 这里扩展了用户的信息
    '''
    # 与 User 模型构成一对一关系, 其中on_delete=models.CASCADE 表示user删除时 同时自动删除profile
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    # 学校 构成一对多的模式， 即一个学校可以拥有多个学生， 当学校删除时， 用户也一并删除
    school = models.ForeignKey(School, on_delete=models.CASCADE, related_name='school')
    # 用户手机号
    phone = models.CharField(max_length=20, blank=True)
    # 用户角色（权限） 用户可以使‘项目发布者’， ‘项目参与者’
    # 枚举列表
    TEACHER = 'TE'  # 项目发布者
    STUDENT = 'ST'  # 项目参与者
    ROLE_CHOICES = (
        (TEACHER, '项目发布者'),
        (STUDENT, '项目参与者'),
    )
    role = models.CharField(
        max_length=2,
        choices=ROLE_CHOICES,
        default=STUDENT,
    )
    # 用户头像
    avatar = models.ImageField(upload_to='avatar/%Y%m%d/', blank=True)
    # 个人介绍, 使用富文本编辑器
    body = RichTextField()

    class Meta:
        '''
        该类用于存储模型的别名等项目
        '''
        verbose_name = '用户详情'
        verbose_name_plural = '用户详情'

    def __str__(self):
        """
        返回模型的所属用户的用户名， 用于优化在admin页面的显示

        Args:
            None

        Returns:
            str: 返回模型的所属用户的用户名

        """
        return self.user.username

lilac_website/user/forms.py
# coding: utf-8

from django import forms
from django.contrib.auth.models import User
from .models import School, Profile


class UserLoginForm(forms.Form):
    '''
    用于定义用户登录时要填写的表格内容
    '''
    username = forms.CharField()
    password = forms.CharField()


class UserRegisterForm(forms.ModelForm):
    '''
        定义用户注册表单
        其中复写了password字段
    '''
    # 复写 User 的密码
    password = forms.CharField()
    password2 = forms.CharField()
    # 复写email字段
    email = forms.EmailField()

    class Meta:
        '''
            定义元数据, 使用User模型, 设置默认需要填写的内容
        '''
        model = User
        fields = ('username', 'first_name', 'last_name')

    def clean_password2(self):
        '''
            对两次输入的密码是否一致进行检查

            Args:
                None

            Returns:
                返回匹配的密码, 或者返回错误信息
        '''
        data = self.cleaned_data
        if data.get('password') == data.get('password2'):
            return data.get('password')
        else:
            raise forms.ValidationError("密码输入不一致,请重试。")

    def clean_email(self):
        '''
            对输入的email进行检查是否为可注册邮箱, 验证邮箱是否唯一
            Args:
                None

            Returns:
                返回匹配的email
                或者返回错误信息
        '''
        data = self.cleaned_data
        user_email = data.get('email')
        username = data.get('username')
        # 检查邮箱是否存在
        if user_email and User.objects.filter(email=user_email).exclude(username=username).exists():
            raise forms.ValidationError(u'Email addresses must be unique.')

        user_email_domin = user_email[(user_email.find('@')+1):]  # 取出用户邮箱域名
        schools = School.objects.all()
        for school in schools:
            if user_email_domin in school.school_emails:
                return data.get('email')
        raise forms.ValidationError("该邮箱暂不支持")


class ProfileRegisterForm(forms.ModelForm):
    '''
    定义注册时, 用户的扩展表单
    '''
    school = forms.IntegerField()  # 用于存储所选学校的id

    class Meta:
        '''
            定义元数据, 使用Profile模型, 必须填写school 和 phone字段
        '''
        model = Profile
        fields = ('phone',)


class ProfileEditForm(forms.ModelForm):
    '''
    定义用户编辑个人资料时, 用户的扩展表单
    '''
    class Meta:
        '''
            定义元数据, 使用Profile模型, 必须填写school 和 phone字段
        '''
        model = Profile
        fields = ('phone', 'avatar', 'body',)

lilac_website/user/views.py
# coding: utf-8

from django.views import View
from django.shortcuts import render, HttpResponse, redirect
# 用户模型
from django.contrib.auth.models import User
# 快捷方式 获取用户或者404
from django.shortcuts import get_object_or_404
# 认证组件
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.hashers import check_password
# 验证登录修饰器
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
# 自定义表格
from .forms import UserLoginForm, UserRegisterForm, ProfileRegisterForm, ProfileEditForm
from .models import School, Profile


# Create your views here.
def user_login(request):
    """
        登录页面的view方法, 自动调用django的认证模块的登录

        Args:
            None

        Returns:
            None
    """
    if request.method == 'POST':
        user_login_form = UserLoginForm(data=request.POST)
        if user_login_form.is_valid():
            data = user_login_form.cleaned_data
            user = authenticate(username=data['username'],
                                password=data['password'])
            if user:
                login(request, user)
                return HttpResponse("TODO: 登录成功")
            else:
                return HttpResponse("账号或密码错误")
        else:
            return HttpResponse("账号或密码输入不合法")
    elif request.method == 'GET':
        user_login_form = UserLoginForm()
        context = {'form': user_login_form}
        return render(request, 'user/login.html', context)
    else:
        return HttpResponse("请使用POST或者GET方法")


def user_logout(request):
    """
        注销页面的view方法, 自动调用django的认证模块的logout

        Args:
            None

        Returns:
            None
    """
    logout(request)
    return HttpResponse("TODO: 登出成功")


# 用户注册
class UserRegisterView(View):
    '''
        用户注册时调用的类视图
    '''
    def get(self, request):
        '''
            返回注册页面
            Args:
                request: 系统请求类, 包含用户必要的信息

            Returns:
                render: 返回渲染的注册页面
        '''
        user_register_form = UserRegisterForm()
        profile_register_form = ProfileRegisterForm()
        school_list = School.objects.all().values('id', 'school_name')
        context = {
            'form': user_register_form,
            'profile_form': profile_register_form,
            'school_list': school_list
        }
        return render(request, 'user/register.html', context)

    def post(self, request):
        '''
            处理用户注册表单
            Args:
                request: 系统请求类, 包含用户必要的信息

            Returns:
                render: 注册结果, TODO 如果注册成功, 自动登录, 并自动跳转到某一页面
        '''
        user_register_form = UserRegisterForm(data=request.POST)
        profile_register_form = ProfileRegisterForm(data=request.POST)
        if user_register_form.is_valid() and profile_register_form.is_valid():
            new_user = user_register_form.save(commit=False)
            user_register_form_data = user_register_form.cleaned_data
            userprofile_form_data = profile_register_form.cleaned_data
            # 设置密码
            new_user.set_password(user_register_form_data['password'])
            # 设置email
            new_user.email = user_register_form_data['email']
            new_user.save()
            # 保存用户的扩展信息
            new_user_profile = profile_register_form.save(commit=False)
            new_user_profile.user = new_user  # 与用户进行链接
            school = get_object_or_404(School, pk=userprofile_form_data['school'])
            new_user_profile.school = school
            new_user_profile.save()
            # 保存好数据后立即登录并返回博客列表页面
            login(request, new_user)
            return redirect('user:edituserinfo', id=new_user.id)
        else:
            # 这里回返回错误信息, 但是实际的时候使用ajax更改页面禁止提交, 这里只是考虑非法提交绕过ajax时候的情况
            return HttpResponse("填写信息有误, 请重新填写<br>错误信息: <br>" +
                                user_register_form.errors.as_text() +
                                profile_register_form.errors.as_text())


# 验证用户注册时填写的信息
def user_signup_in_validate(request):
    '''
        验证用户登录或者注册时候的信息合法性, 这是暴露给AJAX的接口
        Args:
            request: 系统请求类, 包含AJAX提交的信息

        Returns:
            render: 返回验证的结果
    '''
    data = request.POST  # 拿去post数据
    on_validate_type = data.get('type')

    if on_validate_type == 'login':
        # 以下是登录验证
        username = data.get('username')
        password = data.get('password')
        if User.objects.filter(username__iexact=username).exists():
            user = User.objects.get(username__iexact=username)
            if check_password(password, user.password):
                return HttpResponse('200')
            else:
                # 错误的密码
                return HttpResponse('403')
        else:
            # 找不到的用户名
            return HttpResponse('403')
    # ---------------------以下是注册验证---------------------
    elif on_validate_type == 'username':
        if User.objects.filter(username__iexact=data.get('username')).exists():
            # 用户名存在
            return HttpResponse('403')
        # 用户名可以注册
        return HttpResponse('200')
    elif on_validate_type == 'email':
        user_email = data.get('email')
        # 检查邮箱是否存在
        if User.objects.filter(email__iexact=user_email).exists():
            # 邮箱已经被注册了
            return HttpResponse('403')
        # 检查邮箱是否在可用列表中
        user_email_domin = user_email[(user_email.find('@')+1):]  # 取出用户邮箱域名
        schools = School.objects.all()
        for school in schools:
            if user_email_domin in school.school_emails:
                return HttpResponse('200')
        # 邮箱不在可注册列表中
        return HttpResponse('404')
    # 非法的数据格式
    return HttpResponse('403')


# 修改用户信息
class UserInfoChangeView(View):
    '''
        用户修改个人信息时调用的类视图, 所有请求需要验证登录
    '''
    @method_decorator(login_required(login_url='/user/login/'))
    def post(self, request, id):
        '''
            返回注册页面
            Args:
                request: 系统请求类, 包含用户必要的信息
                id: User的id, pk
            Returns:
                render: 返回渲染的修改用户信息的页面
        '''
        user = get_object_or_404(User, pk=id)
        # 判断profile是否存在,如果不存在就新建, 如果存在就不创建
        if Profile.objects.filter(user_id=id).exists():
            profile = Profile.objects.get(user_id=id)
        else:
            profile = Profile.objects.create(user=user)
        # 验证修改数据者，是否为用户本人
        if request.user != user:
            return HttpResponse("你没有权限修改此用户信息")

        profile_form = ProfileEditForm(data=request.POST, files=request.FILES)
        if profile_form.is_valid():
            # 取得清洗后的合法数据
            profile_cd = profile_form.cleaned_data
            profile.phone = profile_cd['phone']
            profile.body = profile_cd['body']
            profile.avatar = profile_cd['avatar']
            profile.save()
            # 带参数的 redirect()
            return HttpResponse("修改成功")
        else:
            return HttpResponse("注册表单输入有误。请重新输入~")

    @method_decorator(login_required(login_url='/user/login/'))
    def get(self, request, id):
        '''
            返回注册页面
            Args:
                request: 系统请求类, 包含用户必要的信息
                id: User的id, pk
            Returns:
                render: 返回渲染的修改用户信息的页面
        '''
        user = get_object_or_404(User, pk=id)
        if request.user == user:
            # 判断profile是否存在,如果不存在就新建, 如果存在就不创建
            if Profile.objects.filter(user_id=id).exists():
                profile = Profile.objects.get(user_id=id)
            else:
                profile = Profile.objects.create(user=user)
            profile_form = ProfileEditForm(initial={'body': profile.body})  # 为了使用富文本编辑器, 将个人简介加入到初始化内容当中
            context = {'profile': profile, 'user': user, 'bio_form': profile_form}
            return render(request, 'user/edit.html', context)
        else:
            return HttpResponse('403 您无权访问')


# 查看用户信息
@login_required(login_url='/user/login/')
def user_info(request, id):
    user = get_object_or_404(User, pk=id)
    profile = user.profile
    is_admin = profile.role == 'TE'

    if request.user == user or is_admin:
        # 可以查询详细信息
        context = {
            'user': user,
            'profile': profile,
        }
        return render(request, 'user/userinfo.html', context)
    else:
        # 只能查询部分信息
        mini_user = {
            'name': user.last_name + user.first_name,
        }
        mini_profile = {
            'avatar': profile.avatar,
            'school': profile.school,
            'body': profile.body,
        }
        context = {
            'user': mini_user,
            'profile': mini_profile,
        }
        return render(request, 'user/userinfo.html', context)

lilac_website/templates/user/edit.html
{% extends "base.html" %} {% load staticfiles %}
{% block title %} 编辑用户信息 {% endblock title %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <!-- 显示用户名 -->
            <br>
            <div class="col-md-4">用户名: {{ user.username }}</div>
            <br>
            <!-- 显示姓名 -->
            <div class="col-md-4">姓名: {{ user.last_name }}{{ user.first_name }}</div>
            <br>
            <!-- 显示学校 -->
            <div class="col-md-4">学校: {{ profile.school.school_name }}</div>
            <br>
            <!-- 显示头像 -->
            {% if profile.avatar %}
                <div class="col-md-4">头像</div>
                <img src="{{ profile.avatar.url }}" style="max-width: 20%; border-radius: 15%;" class="col-md-4">
            {% else %}
                <img src="{% static '/avatar/noavatar.jpeg' %}"  alt="暂无头像" height="150"/>
            {% endif %}
            <br>

            <form method="post" action="." enctype="multipart/form-data">
                {% csrf_token %}
                <!-- avatar -->
                <div class="form-group">
                    <label for="avatar">上传头像</label>
                    <input type="file" class="form-control-file" name="avatar" id="avatar">
                </div>

                <!-- phone -->
                <div class="form-group col-md-4">
                    <label for="phone">电话</label>
                    <input type="text" class="form-control" id="phone" name="phone" value="{{ profile.phone }}">
                </div>
                <!-- bio -->
                <div class="form-group col-md-12">
                    <label for="bio">简介</label>
                    
                    {% comment %} <script src="https://cdn.ckeditor.com/4.13.0/standard/ckeditor.js"></script>
                    <textarea type="text" class="ckeditor" id="bio" name="bio" rows="12">{{ profile.body }}</textarea> {% endcomment %}
                    <div>
                        {{ bio_form.media }}
                        {{ bio_form.body }}
                    </div>
                </div>
                <!-- 提交按钮 -->
                <button type="submit" class="btn btn-primary">提交</button>
            </form>
        </div>
    </div>
</div>

{% endblock content %}

{% block script %}
<!-- 添加富文本编辑器的自适应功能 -->
<script>
    $(".django-ckeditor-widget").removeAttr('style');
</script>
{% endblock script %}

lilac_website/templates/user/login.html
{% extends "base.html" %} {% load staticfiles %}
{% block title %} 登录 {% endblock title %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-lg-5 col-md-4 col-sm-3 col-2"></div>
            <br>
            <form class="login" id="login_form" method="post" action=".">
                {% csrf_token %}
                <!-- 账号 -->
                <br>
                <br>
                <br>
                <div class="form-group">
                    <label for="username">账号</label>
                    <input type="text" name="username" placeholder="请输入用户名" autofocus="autofocus" required
                            id="id_username" class="form-control" />
                </div>
                <small class="form-text text-muted ml-1">
                    还没有账号？
                    <a href="{% url 'user:register' %}" style="color: cornflowerblue; ">
                        注册新账号
                    </a>
                </small>
                <!-- 密码 -->
                <div class="form-group">
                    <label for="password">密码</label>
                    <input type="password" class="form-control" id="password" name="password">
                </div>
                <!-- 提交按钮, 两个按钮, 提交按钮被隐藏, 由js触发 -->
                <button class="primaryAction btn btn-primary" type="submit" hidden id="submit_login">确认</button>
                <button class="primaryAction btn btn-primary" type="button" id="on_submit_login">确认</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

{% block script %}
<script src="{% static 'csrf.js' %}"></script>
<script>
    // login提交验证
const on_submit_login = $('#on_submit_login');
on_submit_login.on('click', async function (event) {
    console.log('in on click');
    on_submit_login.attr('disabled', 'disabled').empty().append('确认中.. ').append(
        '<span class="spinner-border spinner-border-sm text-light" role="status">\n' +
        '  <span class="sr-only">Loading...</span>\n' +
        '</span>'
    );

    const params = $("#login_form").serializeArray();
    let data = {};
    for (let x in params) {
        data[params[x].name] = params[x].value;
    }
    console.log(data)

    let is_login_pass = await login_validate({
        'type': 'login',
        'username': data.username,
        'password': data.password
    });

    if (is_login_pass) {
        $('#submit_login').click();
    } else {
        on_submit_login.removeAttr('disabled').empty().append('确认 &raquo;');
        layer.msg('账号或密码错误<br/>重新试一下呗~')
    }
});

const login_validate = async (data) => {
    console.log(data)
    let res = await $.post("{% url 'user:user_signinup_validate' %}", data).fail((response) => {
        on_submit_login.removeAttr('disabled').empty().append('确认 &raquo;');
        layer.msg('与服务器通讯失败..<br/>重试一下呗o(╥﹏╥)o')
    });

    if (res === '200') {
        return true;
    } else {
        return false;
    }
};
</script>
{% endblock script %}

lilac_website/templates/user/register.html
{% extends "base.html" %} {% load staticfiles %}
{% block title %} 注册 {% endblock title %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <form class="signup" id="signup_form" method="post" action=".">
                {% csrf_token %}
                <!-- 账号 -->
                <div class="form-group col-md-4">
                    <label for="username">用户名</label>
                    <input type="text" class="form-control" id="id_username" name="username" required>
                </div>
                <!-- 姓名 -->
                <div class="form-group col-md-4">
                    <label for="username">姓</label>
                    <input type="text" class="form-control" id="last_name" name="last_name" required>
                </div>
                <div class="form-group col-md-4">
                    <label for="username">名</label>
                    <input type="text" class="form-control" id="first_name" name="first_name" required>
                </div>
                <!-- 学校 -->
                <div class="form-group col-md-4">
                    <label for="email">学校</label>
                    <p><select name="school" required id="id_school">
                        <option id="name" value="" selected>---------</option>
                        {% for school in school_list %}
                        <option id="name" value="{{school.id}}">{{school.school_name}}</option>
                        {% endfor %}
                    </select></p>
                </div>
                <!-- 手机 -->
                <div class="form-group col-md-4">
                    <label for="email">手机</label>
                    <input type="text" class="form-control" id="id_phone" name="phone">
                </div>
                <!-- 邮箱 -->
                <div class="form-group col-md-4">
                    <label for="email">Email</label>
                    <input type="text" class="form-control" id="id_email" name="email">
                </div>
                <!-- 密码 -->
                <div class="form-group col-md-4">
                    <label for="password">设置密码</label>
                    <input type="password" class="form-control" id="id_password1" name="password" required>
                </div>
                <!-- 确认密码 -->
                <div class="form-group col-md-4">
                    <label for="password2">确认密码</label>
                    <input type="password" class="form-control" id="id_password2" name="password2" required>
                </div>
                <!-- 提交按钮 -->
                <button type="submit" class="btn btn-primary" id="submit_signup" hidden>确认 &raquo;</button>
                <button type="button" class="btn btn-primary" id="on_submit_signup">确认 &raquo;</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

{% block script %}
<script src="{% static 'csrf.js' %}"></script>
<script>
$(() => {
    // username 验证
    const on_submit_signup = $('#on_submit_signup');
    const username_input = $('#id_username');
    username_input.on('change', (event) => {
        let data = {
            'username': event.delegateTarget.value,
            'type': 'username'
        };
        username_validate(data);
    });

    const username_validate = async (data) => {
        if (!data.username) {
            username_input.addClass('breath-input');
            var username_tips = layer.tips('请填写用户名', username_input, {
                time: 4000,
                area: ['auto', 'auto'],
                tips: [2, 'indianred'],
                tipsMore: true
            });
            return false;
        }
        let res = await $.post("{% url 'user:user_signinup_validate' %}", data,
            function (data, status) {
                if (data === '403') {
                    username_input.addClass('breath-input');
                    var username_tips = layer.tips('用户名已被注册', username_input, {
                        time: 4000,
                        area: ['auto', 'auto'],
                        tips: [2, 'indianred'],
                        tipsMore: true
                    });
                } else {
                    username_input.removeClass('breath-input');
                }
            },
        ).fail((response) => {
            on_submit_signup.removeAttr('disabled').empty().append('确认 &raquo;');
            layer.msg('与服务器通讯失败..<br/>重试一下呗o(╥﹏╥)o')
        });

        if (res === '200') {
            return true;
        } else {
            return false;
        }
    };

    // email 验证
    const email_input = $('#id_email');
    email_input.on('change', (event) => {
        let data = {
            'email': event.delegateTarget.value,
            'type': 'email'
        };
        email_validate(data);
    });

    const email_validate = async (data) => {
        if (!data.email) {
            email_input.addClass('breath-input');
            var email_tips = layer.tips('请填写邮箱哟', email_input, {
                time: 4000,
                area: ['auto', 'auto'],
                tips: [2, 'indianred'],
                tipsMore: true
            });
            return false;
        }
        let res = await $.post("{% url 'user:user_signinup_validate' %}", data,
            function (data, status) {
                if (data === '403') {
                    email_input.addClass('breath-input');
                    var email_tips = layer.tips('此邮箱已被注册', email_input, {
                        time: 4000,
                        area: ['auto', 'auto'],
                        tips: [2, 'indianred'],
                        tipsMore: true
                    });
                } else if (data === '404'){
                    email_input.addClass('breath-input');
                    var email_tips = layer.tips('在邮箱暂时不在可注册列表中', email_input, {
                        time: 4000,
                        area: ['auto', 'auto'],
                        tips: [2, 'indianred'],
                        tipsMore: true
                    });
                }else{
                    email_input.removeClass('breath-input');
                }
            },
        ).fail((response) => {
            on_submit_signup.removeAttr('disabled').empty().append('确认 &raquo;');
            layer.msg('与服务器通讯失败..<br/>重试一下呗o(╥﹏╥)o')
        });

        if (res === '200') {
            return true;
        } else {
            return false;
        }
    };

    // password1 验证
    const password1_input = $('#id_password1');
    password1_input.on('change', (event) => {
        let password1 = event.delegateTarget.value;
        password1_validate(password1);
    });

    const password1_validate = (password1) => {
        console.log(typeof(password1))
        const regNumber = /\d+/;
        const regString = /[a-zA-Z]+/;
        if (!regNumber.test(password1) || !regString.test(password1) || password1.length < 8) {
            console.log(regNumber.test(password1))
            console.log(regString.test(password1))
            
            console.log(password1.length < 8)
            password1_input.addClass('breath-input');
            var password1_tips = layer.tips('请输入8位或以上字母/数字组合', password1_input, {
                time: 4000,
                area: ['auto', 'auto'],
                tips: [2, 'indianred'],
                tipsMore: true
            });
            return false;
        } else {
            password1_input.removeClass('breath-input');
            return true;
        }
    };

    // password2 验证
    const password2_input = $('#id_password2');
    password2_input.on('change', (event) => {
        let password2 = event.delegateTarget.value;
        password2_validate(password2);
    });

    const password2_validate = (password2) => {
        if (password2 !== password1_input.val()) {
            password2_input.addClass('breath-input');
            var password2_tips = layer.tips('两次输入密码不一致', password2_input, {
                time: 4000,
                area: ['auto', 'auto'],
                tips: [2, 'indianred'],
                tipsMore: true
            });
            return false;
        } else {
            password2_input.removeClass('breath-input');
            return true;
        }
    };

    // 提交验证
    on_submit_signup.on('click', async function (event) {

        on_submit_signup.attr('disabled', 'disabled').empty().append('确认中.. ').append(
            '<span class="spinner-border spinner-border-sm text-light" role="status">\n' +
            '  <span class="sr-only">Loading...</span>\n' +
            '</span>'
        );

        const params = $("#signup_form").serializeArray();
        let data = {};
        for (let x in params) {
            data[params[x].name] = params[x].value;
        }
        console.log(data)
        let is_password2_pass = password2_validate(data.password2);
        let is_password1_pass = password1_validate(data.password);
        let is_email_pass = await email_validate({
            'type': 'email',
            'email': data.email
        });
        let is_username_pass = await username_validate({
            'type': 'username',
            'username': data.username
        });

        if (is_password1_pass && is_password2_pass && is_username_pass && is_email_pass) {
            $('#submit_signup').click();
        } else {
            on_submit_signup.removeAttr('disabled').empty().append('确认 &raquo;');
        }
    });
});
</script>
{% endblock script %}

lilac_website/templates/user/userinfo.html
{% extends "base.html" %} {% load staticfiles %}
{% block title %} 用户信息 {% endblock title %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <!-- 显示用户名 -->
            {% if user.username %}
                <br>
                <div class="col-md-4">用户名: {{ user.username }}</div>
                <br>
            {% endif %}
            <!-- 显示姓名 -->
            <div class="col-md-4">姓名: {{ user.last_name }}{{ user.first_name }}</div>
            <br>
            <!-- 显示学校 -->
            <div class="col-md-4">学校: {{ profile.school.school_name }}</div>
            <br>
            <!-- 显示头像 -->
            {% if profile.avatar %}
                <div class="col-md-4">头像</div>
                <img src="{{ profile.avatar.url }}" style="max-width: 20%; border-radius: 15%;" class="col-md-4">
            {% else %}
                <img src="{% static '/avatar/noavatar.jpeg' %}"  alt="暂无头像" height="150"/>
            {% endif %}
            <br>
            <!-- 显示电话 -->
            {% if profile.phone %}
                <br>
                <div class="col-md-4">电话: {{ profile.phone }}</div>
                <br>
            {% endif %}
            <!-- 显示简介 -->
            <br>
            <label for="bio">简介</label>
            <div class="col-md-12">{{ profile.body }}</div>
            <br>
        </div>
    </div>
</div>

{% endblock content %}

{% block script %}

{% endblock script %}