lilac_website/home/urls.py
# coding: utf-8
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
app_name = 'home'

urlpatterns = [
    #显示主页
    path('', views.show_home, name = 'homepage')
]

lilac_website/lilac_website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('project/', include('project.urls', namespace='project')),
    path('user/', include('user.urls', namespace='user')),
    path('comment/', include('comment.urls', namespace='comment')),
    path('', include('home.urls', namespace='home')),
]

# 增加媒体文件文件的路径
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lilac_website/project/urls.py
# coding: utf-8
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
app_name = 'project'

urlpatterns = [
    # 项目列表
    path('list/', views.project_view().show_list, name = 'project_list'),
    # 项目详情
    path('detail/<int:id>/', views.project_view().show_detail, name = 'project_detail'),
    # 发布新项目
    path('create/', views.project_view().project_create, name = 'project_create'),
    # 更新项目
    path('update/<int:id>/', views.project_view().project_update, name = 'project_update'),
    # （安全）删除项目
    path('safe_delete/<int:id>/', views.project_view().project_delete, name = 'project_safe_delete'),
    # 添加申请者
    path('apply/<int:id>/', views.project_view().project_apply, name = 'project_apply')
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lilac_website/project/models.py
# coding: utf-8

from django.db import models
# 引入时区支持
from django.utils import timezone
# 引入用户模型
from django.contrib.auth.models import User
# 引入taggit的标签，作为文章关键字
from taggit.managers import TaggableManager
# 引入django-ckeditor 实现富文本编辑器的功能
from ckeditor.fields import RichTextField
# 引入imagekit, 用于自动处理用户上传的图片
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFit



# Create your models here.
class ProjectPage(models.Model):
    '''
    该类是一个基础项目模型类，网站中的每个发起的项目，都是填充这个表的内容
    '''
    # 文章标题图, 图片处理的方法仅按照教程中给出，具体的需要具体摸索
    avatar = ProcessedImageField(
        upload_to='project/%Y%m%d',
        processors=[ResizeToFit(width=400)],
        format='JPEG',
        options={'quality': 100},
        blank=True
    )
    # 主页项目
    is_homepage = models.BooleanField('是否在主页可见', default=False)
    # 是否在项目页可见, 因为首页可能有一些紫丁香相关的介绍, 因此需要一些非项目的文章
    # 该字段用于确保非项目的文章在项目页不被显示
    is_project = models.BooleanField('是否在项目页可见', default=True)
    # 文章标题
    title = models.CharField(max_length=100)
    # 摘要, 不超过500字
    abstract = models.CharField(max_length=500)
    # 关键字
    tags = TaggableManager(blank=True)
    # 文章正文， 使用富文本编辑器
    body = RichTextField()
    # 发起者, 一对多， 即一个内容发布者可以发布多个项目， 当内容发起者被删除时，其发布的项目同样被删除
    publisher = models.ForeignKey(User, on_delete=models.CASCADE, related_name='publisher')
    # 参与者, 多对多， 即一个项目可以有多个参与者， 一个参与者可以参与多个项目
    workers = models.ManyToManyField(User)
    # 申请者, 多对多， 即一个项目可以有多个申请者， 一个申请者可以申请多个项目
    applicants = models.ManyToManyField(User,related_name='applicants',blank = True)
    # 创建时间
    created = models.DateTimeField(default=timezone.now)
    # 文章更新时间
    updated = models.DateTimeField(auto_now=True)
    # 文章浏览量
    total_views = models.PositiveIntegerField(default=0)

    class Meta:
        '''
        该类用于存储模型的别名等项目
        '''
        verbose_name = '项目'
        verbose_name_plural = '项目'
        ordering = ('-created', )  # 默认按创建时间进行排序

    def __str__(self):
        """
        返回模型的标题字段， 用于优化在admin页面的显示

        Args:
            None

        Returns:
            str: 返回模型的标题字段

        """
        return self.title




class HomeProject(models.Model):
    '''
        主页项目类，从基础项目模型类中得出is_homepage
    '''
    # 主页项目 基础项目模型类中 is_homepage == True 的项目
    Home_Project = models.OneToOneField(ProjectPage, on_delete=models.CASCADE, null=True)
    class Meta:
        '''
        该类用于存储模型的别名等项目
        '''
        verbose_name = '主页项目'
        verbose_name_plural = '主页项目'

    def __str__(self):
        """
        返回模型的标题字段， 用于优化在admin页面的显示

        Args:
            None

        Returns:
            str: 返回模型的标题字段

        """
        return self.Home_Project.title

lilac_website/templates/project/project_create.html
{% extends "base.html" %}
{% load staticfiles %}

<!-- 写入 base.html 中定义的 title -->
{% block title %} 发布项目 {% endblock title %}
<!-- 写入 base.html 中定义的 content -->
{% block content %}
<!-- 写项目表单 -->
<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <!-- 提交项目的表单 -->
            <form method="post" action="." enctype="multipart/form-data">
                <!-- Django中需要POST数据的地方都必须有csrf_token -->
                {% csrf_token %}
                <!-- 项目标题 -->
                <div class="form-group">
                    <label for="title">项目标题</label>
                    <input type="text" class="form-control" id="title" name="title">
                </div>
                <!-- 项目摘要 -->
                <div class="form-group">
                    <label for="abstract">项目摘要</label>
                    <input type="text" class="form-control" id="abstract" name="abstract">
                </div>
                <!-- 关键词 -->
                <div class="form-group">
                    <label for="tags">关键词</label>
                    <input type="text" class="form-control col-3" id="tags" name="tags">
                    <p class="help-block" style="color: rgb(180, 180, 180);">请使用逗号分隔关键词</p>
                </div>
                <!-- 项目正文 -->
                <div class="form-group">
                    <label>详细方案</label>
                    <hr>
                    {{ project_form.media }}
                    {{ project_form.body }}
                    <hr>
                </div>
                <!-- 上传标题图 -->
                <div class="form-group">
                    <label for="avatar">上传标题图</label>
                    <input type="file" class="form-control-file" name="avatar" id="avatar">
                </div>
                <!-- 提交按钮 -->
                <button type="submit" class="btn btn-primary">完成</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

lilac_website/templates/project/project_detail_other.html
{% extends "base.html" %}
{% load staticfiles %}
<!-- 写入 base.html 中定义的 title -->
{% block title %}
    项目详情
{% endblock title %}

<!-- 写入 base.html 中定义的 content -->
{% block content %}
<!-- 项目详情 -->
<div class="container">
    <div class="row">
        <!-- 标题 -->
        <h1 style="text-align:center" class="col-12 mt-4 mb-4">{{ project.title }}</h1>
        <div class="col-sm-9">
            <!-- 发布者 -->
            <div class="col-12 alert alert-success">
                发布者：{{ project.publisher }}
            </div>
            <!-- 参与者 -->
            <div class="col-12 alert alert-success">当前参与者：
            {% for worker in project.workers.all %}
                {{ worker.username }}
            {% endfor %}
            </div>
            <!-- 摘要 -->
            <div class="col-12 alert alert-success">摘要：{{ project.abstract }}</div>
            <!-- 关键字 -->
            <div class="col-12 alert alert-success">关键词：
            {% for tag in project.tags.all %}
                {{ tag }}
            {% endfor %}
            </div>
        </div>
        <!-- 标题图 -->
        {% if project.avatar %}
        <div class="col-sm-3">
            <img class="img-responsive" height="250px" src="{{ project.avatar.url }}">
        </div>
            {% endif %}
        <!-- 项目正文 -->
        <div class="col-12">
            <h2>详细方案：</h2>
            <!-- 报名按钮 -->
            <div style="text-align:right">
                {% if request.user in project.workers.all %}
                    <button type="button" class="btn btn-default">已经是参与者</button>
                {% elif request.user in project.applicants.all %}
                    <button type="button" class="btn btn-default">已申请，尚未通过</button>
                {% else %}
                    <button type="button" class="btn btn-primary" onclick="apply()">报名参加该项目</button>
                {% endif %}
            </div>
            <hr>
            <p>{{ project.body|safe }}</p>
            <hr>
        </div>
    </div>
    <!-- 时间信息 -->
    <div>
        <p class="text-right"><em>项目发布时间：{{ project.created }}</em></p>
        <p class="text-right"><em>最新更新时间：{{ project.updated }}</em></p>
    </div>
</div>
<script>
//实现报名前弹窗功能
    function apply() {
        // 调用layer弹窗组件
        layer.open({
            // 弹窗标题
            title: "确认报名",
            // 正文
            content: "确认报名参加该项目吗？",
            // 点击确定按钮后调用的回调函数
            yes: function(index, layero) {
                // 指定应当前往的 url
                location.href='{% url "project:project_apply" project.id %}'
            },
        })
    }
</script>
{% endblock content %}

lilac_website/templates/project/project_detail_self.html
{% extends "base.html" %}
{% load staticfiles %}
<!-- 写入 base.html 中定义的 title -->
{% block title %}
    项目详情
{% endblock title %}

<!-- 写入 base.html 中定义的 content -->
{% block content %}
<!-- 项目详情 -->
<div class="container">
    <div class="row">
        <h1 style="text-align:center" class="col-12 mt-4 mb-4">{{ project.title }}</h1>
        <div class="col-sm-9">
            <div class="col-12 alert alert-success">
                发布者：{{ project.publisher }}
                <a href="#" onclick="confirm_safe_delete()">删除项目</a>
                <a href="{% url 'project:project_update' project.id %}">更新项目内容</a>
            </div>
            <!-- 表单跳转删除项目 -->
            <form
            style="display:none;"
            id="safe_delete"
            action="{% url 'project:project_safe_delete' project.id %}"
            method="POST"
            >
            {% csrf_token %}
                <button type="submit">发送</button>
            </form>
            <!-- 参与者 -->
            <div class="col-12 alert alert-success">当前参与者：
            {% for worker in project.workers.all %}
                {{ worker.username }}
            {% endfor %}
            </div>
            <!-- 摘要 -->
            <div class="col-12 alert alert-success">摘要：{{ project.abstract }}</div>
            <!-- 关键字 -->
            <div class="col-12 alert alert-success">关键字：
            {% for tag in project.tags.all %}
                {{ tag }}
            {% endfor %}
            </div>
            </div>
            <!-- 标题图 -->
            {% if project.avatar %}
            <div class="col-sm-3">
                <img class="img-responsive" height="250px" src="{{ project.avatar.url }}">
            </div>
            {% endif %}
        <!-- 项目正文 -->
        <div class="col-12">
            <h2>详细方案：</h2>
            <hr>
            <p>{{ project.body|safe }}</p>
            <hr>
        </div>
    </div>
    <!-- 报名者列表 -->
    <div class="form-group">
        <label>当前报名者列表</label>
        <select id="select_list" class="form-control" multiple="multiple" size="5">
            {% for applicant in project.applicants.all %}
            <option>{{ applicant.username }}</option>
            {% endfor %}
        </select>
	</div>
    <!-- 时间信息 -->
    <div>
        <p class="text-right"><em>项目发布时间：{{ project.created }}</em></p>
        <p class="text-right"><em>最新更新时间：{{ project.updated }}</em></p>
    </div>
</div>
<script type="text/javascript">

</script>
<script>
//实现删除文章前弹窗功能
function confirm_safe_delete() {
    layer.open({
        title: "确认删除",
        content: "确认删除项目吗？",
        yes: function(index, layero) {
            $('form#safe_delete button').click();
            layer.close(index);
        }
    })
}
</script>
{% endblock content %}

lilac_website/templates/project/project_list.html
{% extends "base.html" %}
{% load staticfiles %}

<!-- 写入 base.html 中定义的 title -->
{% block title %}
    项目列表
{% endblock title %}

<!-- 写入 base.html 中定义的 content -->
{% block content %}

<!-- 定义放置文章标题的div容器 -->
<div class="container">
    <div class="row mt-2">
        <!-- 提示信息 -->
        {% if messages %}
        <script>
            {% for msg in messages %}
                alert('{{ msg.message }}');
            {% endfor %}
         </script>
        {% endif %}

        {% for project in projects %}
        <!-- 项目内容 -->
        <div class="col-4 mb-4">
        <!-- 卡片容器 -->
            <div class="card h-100">
                <!-- 标题 -->
                <h4 class="card-header">{{ project.title }}</h4>
                <!-- 摘要 -->
                <div class="card-body">
                    <p class="card-text">{{ project.abstract|slice:'100' }}...</p>
                </div>
                <!-- 注脚 -->
                <div class="card-footer">
                    <a href="{% url 'project:project_detail' project.id %}" class="btn btn-primary">阅读本项目</a>
                </div>
                <!-- 显示浏览量 -->
                <span>
                <small class="col align-self-end" style="color: gray;">
                    浏览: {{ project.total_views }}
                </small>
                </span>

            </div>
        </div>
        {% endfor %}

    </div>
</div>
<!-- 页码导航 -->
    <div class="pagination row">
        <div class="m-auto">
            <span class="step-links">
            <!-- 如果不是第一页，则显示上翻按钮 -->
                {% if projects.has_previous %}
                <a href="?page=1" class="btn btn-success">
                    &laquo; 首页
                </a>
                <span>...</span>
                <a href="?page={{ projects.previous_page_number }}"
                   class="btn btn-secondary"
                >
                    {{ projects.previous_page_number }}
                </a>
                {% endif %}

                <!-- 当前页面 -->
                <span class="current btn btn-danger btn-lg">
                    {{ projects.number }}
                </span>

                <!-- 如果不是最末页，则显示下翻按钮 -->
                {% if projects.has_next %}
                <a href="?page={{ projects.next_page_number }}"
                   class="btn btn-secondary"
                >
                    {{ projects.next_page_number }}
                </a>
                <span>...</span>
                <a href="?page={{ projects.paginator.num_pages }}"
                   class="btn btn-success"
                >
                    末页 &raquo;
                </a>
                {% endif %}
                </span>
            </div>
        </div>
{% endblock content %}



lilac_website/templates/project/project_update.html
{% extends "base.html" %}
{% load staticfiles %}
<script src="JavaScript/ckeditor/ckeditor.js" type="text/javascript"></script>
{% block title %} 更新项目 {% endblock title %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <form method="post" action="." enctype="multipart/form-data">
                <!-- Django中需要POST数据的地方都必须有csrf_token -->
                {% csrf_token %}
                <!-- 项目标题 -->
                <div class="form-group">
                    <label for="title">项目标题</label>
                    <input type="text" class="form-control" id="title" name="title" value="{{ project.title }}">
                </div>
                <!-- 项目摘要 -->
                <div class="form-group">
                    <label for="abstract">项目摘要</label>
                    <input type="text" class="form-control" id="abstract" name="abstract" value="{{ project.abstract }}">
                </div>
                <!-- 项目关键词 -->
                <div class="form-group">
                    <label for="tags">关键词</label>
                    <input type="text" class="form-control col-3" id="tags" name="tags" >
                    <p class="help-block" style="color: rgb(180, 180, 180);">请使用逗号分隔关键词</p>
                </div>
                <!-- 项目详情 -->
                <div class="form-group">
                    <label>详细方案</label>
                    <hr>
                    {{ project_form.media }}
                    {{ project_form.body }}
                    <hr>
                </div>
                <!-- 参与者列表 -->
                <div id="workers" class="form-group">
                    <label>当前参与者列表:</label>
                    <br>
                    {% for worker in project.workers.all %}
                        {% if worker.username != project.publisher.username %}
                            <label>
                            {{ worker.username }}
                            <input type="checkbox" name="checkbox_worker" value="{{ worker.username }}" onclick="delete_worker()">
                            </label>
                            <br>
                        {% endif %}
                    {% endfor %}
                    <!-- 全部要处理的用户的名字的连接的字符串 -->
                    <input type="text" class="form-control" id="workers_delete" name="workers_delete" style="display:none">
                    <p class="help-block" style="color: rgb(180, 180, 180);">请选中要移除的参与者</p>
	            </div>
                <hr>
                <!-- 申请者列表 -->
                <div id="applicants" class="form-group">
                    <label>当前报名者列表:</label>
                    <br>
                    {% for applicant in project.applicants.all %}
                     <label>
                         {{ applicant.username }}
                         <input type="checkbox" name="checkbox_app_add" value="{{ applicant.username }}" onclick="app()">通过
                         <input type="checkbox" name="checkbox_app_delete" value="{{ applicant.username }}" onclick="app()">不通过
                     </label>
                    <br>
                    {% endfor %}
                    <!-- 全部要处理的用户的名字的连接的字符串 -->
                    <input type="text" class="form-control" id="applicants_add" name="applicants_add" style="display:none">
                    <input type="text" class="form-control" id="applicants_delete" name="applicants_delete" style="display:none">
	            </div>
                <!-- 标题图 -->
                <div class="form-group">
                    <label for="avatar">上传标题图</label>
                    <input type="file" class="form-control-file" name="avatar" id="avatar">
                </div>
                <!-- 提交按钮 -->
                <button type="submit" class="btn btn-primary">完成</button>
            </form>
        </div>
    </div>
</div>
<script type="text/javascript">
    //在标签input中显示标签
    {% for tag in project.tags.all %}
        document.getElementById("tags").value += {{ tag }}
        document.getElementById("tags").value += ","
    {% endfor %}
    str = document.getElementById("tags").value;
    str = str.slice(0,str.length-1);
    document.getElementById("tags").value = str;
</script>
<script type="text/javascript">
    //处理申请者
    function app(){
        app_add = document.getElementsByName("checkbox_app_add");
        app_delete = document.getElementsByName("checkbox_app_delete");
        var text_add = "";
        var text_delete = "";
        for(i=0;i<app_add.length;i++)
        {
            if(app_add[i].checked && app_delete[i].checked)//如果通过与不通过都勾选，则提示不正确，清空改行勾选
            {
                text_add = "";
                text_delete = "";
                alert("请正确勾选");
                app_add[i].checked = false;
                app_delete[i].checked = false;
                break;
            }
            if(app_add[i].checked)
            {
                text_add += app_add[i].value;
                text_add += " ";
            }
            if(app_delete[i].checked)
            {
                text_delete += app_delete[i].value;
                text_delete += " ";
            }
        }
        document.getElementById("applicants_add").value = text_add;
        document.getElementById("applicants_delete").value = text_delete;
    }
    //删除参与者
    function delete_worker(){
        worker_list = document.getElementsByName("checkbox_worker");
        var worker_text = "";
        for(i=0;i<worker_list.length;i++)
        {
            if(worker_list[i].checked)
            {
                worker_text += worker_list[i].value;
                worker_text += " ";
            }
        }
        document.getElementById("workers_delete").value = worker_text;
    }
</script>
{% endblock content %}